import type { MovieDetails, Genre } from './tmdb';

export const MOCK_GENRES: Record<string, Genre[]> = {
  es: [
    { id: 28, name: 'Acción' },
    { id: 12, name: 'Aventura' },
    { id: 16, name: 'Animación' },
    { id: 35, name: 'Comedia' },
    { id: 80, name: 'Crimen' },
    { id: 99, name: 'Documental' },
    { id: 18, name: 'Drama' },
    { id: 10751, name: 'Familia' },
    { id: 14, name: 'Fantasía' },
    { id: 36, name: 'Historia' },
    { id: 27, name: 'Terror' },
    { id: 10402, name: 'Música' },
    { id: 9648, name: 'Misterio' },
    { id: 10749, name: 'Romance' },
    { id: 878, name: 'Ciencia Ficción' },
    { id: 10770, name: 'Película de TV' },
    { id: 53, name: 'Thriller' },
    { id: 10752, name: 'Bélica' },
    { id: 37, name: 'Western' },
  ],
  en: [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 16, name: 'Animation' },
    { id: 35, name: 'Comedy' },
    { id: 80, name: 'Crime' },
    { id: 99, name: 'Documentary' },
    { id: 18, name: 'Drama' },
    { id: 10751, name: 'Family' },
    { id: 14, name: 'Fantasy' },
    { id: 36, name: 'History' },
    { id: 27, name: 'Horror' },
    { id: 10402, name: 'Music' },
    { id: 9648, name: 'Mystery' },
    { id: 10749, name: 'Romance' },
    { id: 878, name: 'Science Fiction' },
    { id: 10770, name: 'TV Movie' },
    { id: 53, name: 'Thriller' },
    { id: 10752, name: 'War' },
    { id: 37, name: 'Western' },
  ],
};

export const MOCK_MOVIES: MovieDetails[] = [
  {
    id: 101,
    title: 'Blade Runner 2049',
    original_title: 'Blade Runner 2049',
    poster_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2017-10-06',
    vote_average: 8.0,
    vote_count: 12500,
    genre_ids: [878, 18, 53],
    genres: [
      { id: 878, name: 'Ciencia Ficción' },
      { id: 18, name: 'Drama' },
    ],
    overview: 'Un joven blade runner descubre un secreto enterrado desde hace mucho tiempo que lo lleva a buscar a Rick Deckard, un antiguo blade runner que ha estado desaparecido durante 30 años.',
    original_language: 'en',
    runtime: 164,
    tagline: 'El futuro es ahora.',
    status: 'Released',
    budget: 150000000,
    revenue: 259200000,
    credits: {
      cast: [
        { id: 1, name: 'Ryan Gosling', character: 'K', profile_path: null },
        { id: 2, name: 'Harrison Ford', character: 'Rick Deckard', profile_path: null },
        { id: 3, name: 'Ana de Armas', character: 'Joi', profile_path: null },
      ],
      crew: [
        { id: 4, name: 'Denis Villeneuve', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 102,
    title: 'The Matrix',
    original_title: 'The Matrix',
    poster_path: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '1999-03-31',
    vote_average: 8.2,
    vote_count: 24000,
    genre_ids: [878, 28],
    genres: [
      { id: 878, name: 'Ciencia Ficción' },
      { id: 28, name: 'Acción' },
    ],
    overview: 'Un hacker informático aprende de rebeldes misteriosos sobre la verdadera naturaleza de su realidad y su papel en la guerra contra sus controladores.',
    original_language: 'en',
    runtime: 136,
    tagline: 'Bienvenido al mundo real.',
    status: 'Released',
    budget: 63000000,
    revenue: 463500000,
    credits: {
      cast: [
        { id: 5, name: 'Keanu Reeves', character: 'Neo', profile_path: null },
        { id: 6, name: 'Laurence Fishburne', character: 'Morpheus', profile_path: null },
        { id: 7, name: 'Carrie-Anne Moss', character: 'Trinity', profile_path: null },
      ],
      crew: [
        { id: 8, name: 'Lana Wachowski', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 103,
    title: 'Inception',
    original_title: 'Inception',
    poster_path: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2010-07-16',
    vote_average: 8.4,
    vote_count: 34000,
    genre_ids: [878, 28, 12],
    genres: [
      { id: 878, name: 'Ciencia Ficción' },
      { id: 28, name: 'Acción' },
    ],
    overview: 'A un ladrón que roba secretos corporativos a través del uso de la tecnología de intercambio de sueños se le da la tarea inversa de plantar una idea en la mente de un CEO.',
    original_language: 'en',
    runtime: 148,
    tagline: 'Tu mente es la escena del crimen.',
    status: 'Released',
    budget: 160000000,
    revenue: 829890000,
    credits: {
      cast: [
        { id: 9, name: 'Leonardo DiCaprio', character: 'Cobb', profile_path: null },
        { id: 10, name: 'Joseph Gordon-Levitt', character: 'Arthur', profile_path: null },
        { id: 11, name: 'Elliot Page', character: 'Ariadne', profile_path: null },
      ],
      crew: [
        { id: 12, name: 'Christopher Nolan', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 104,
    title: 'Pulp Fiction',
    original_title: 'Pulp Fiction',
    poster_path: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '1994-09-10',
    vote_average: 8.5,
    vote_count: 26000,
    genre_ids: [80, 18],
    genres: [
      { id: 80, name: 'Crimen' },
      { id: 18, name: 'Drama' },
    ],
    overview: 'Las vidas de dos asesinos a sueldo, un boxeador, la esposa de un gánster y un par de bandidos se entrelazan en cuatro historias de violencia y redención.',
    original_language: 'en',
    runtime: 154,
    tagline: 'Justo cuando crees que lo has visto todo...',
    status: 'Released',
    budget: 8000000,
    revenue: 213900000,
    credits: {
      cast: [
        { id: 13, name: 'John Travolta', character: 'Vincent Vega', profile_path: null },
        { id: 14, name: 'Samuel L. Jackson', character: 'Jules Winnfield', profile_path: null },
        { id: 15, name: 'Uma Thurman', character: 'Mia Wallace', profile_path: null },
      ],
      crew: [
        { id: 16, name: 'Quentin Tarantino', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 105,
    title: 'Interstellar',
    original_title: 'Interstellar',
    poster_path: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2014-11-05',
    vote_average: 8.4,
    vote_count: 32000,
    genre_ids: [878, 12, 18],
    genres: [
      { id: 878, name: 'Ciencia Ficción' },
      { id: 12, name: 'Aventura' },
    ],
    overview: 'Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.',
    original_language: 'en',
    runtime: 169,
    tagline: 'El fin de la Tierra no será el fin de la humanidad.',
    status: 'Released',
    budget: 165000000,
    revenue: 701700000,
    credits: {
      cast: [
        { id: 17, name: 'Matthew McConaughey', character: 'Cooper', profile_path: null },
        { id: 18, name: 'Anne Hathaway', character: 'Brand', profile_path: null },
        { id: 19, name: 'Jessica Chastain', character: 'Murph', profile_path: null },
      ],
      crew: [
        { id: 12, name: 'Christopher Nolan', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 106,
    title: 'El Viaje de Chihiro',
    original_title: 'Spirited Away',
    poster_path: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2001-07-20',
    vote_average: 8.5,
    vote_count: 15500,
    genre_ids: [16, 14, 12],
    genres: [
      { id: 16, name: 'Animación' },
      { id: 14, name: 'Fantasía' },
    ],
    overview: 'Durante el traslado de su familia al campo, una niña de 10 años vagabundea por un mundo gobernado por dioses, brujas y espíritus, donde los humanos se convierten en bestias.',
    original_language: 'ja',
    runtime: 125,
    tagline: 'Nada de lo que sucede se olvida jamás.',
    status: 'Released',
    budget: 19000000,
    revenue: 395800000,
    credits: {
      cast: [
        { id: 20, name: 'Rumi Hiiragi', character: 'Chihiro', profile_path: null },
        { id: 21, name: 'Miyu Irino', character: 'Haku', profile_path: null },
      ],
      crew: [
        { id: 22, name: 'Hayao Miyazaki', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 107,
    title: 'Parasite',
    original_title: 'Gisaengchung',
    poster_path: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 17000,
    genre_ids: [35, 53, 18],
    genres: [
      { id: 53, name: 'Thriller' },
      { id: 18, name: 'Drama' },
    ],
    overview: 'La discriminación social y la codicia amenazan la relación simbiótica recién formada entre la adinerada familia Park y el indigente clan Kim.',
    original_language: 'ko',
    runtime: 132,
    tagline: 'Encuentra al intruso.',
    status: 'Released',
    budget: 11400000,
    revenue: 258700000,
    credits: {
      cast: [
        { id: 23, name: 'Song Kang-ho', character: 'Ki-taek', profile_path: null },
        { id: 24, name: 'Choi Woo-shik', character: 'Ki-woo', profile_path: null },
      ],
      crew: [
        { id: 25, name: 'Bong Joon-ho', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 108,
    title: 'Drive',
    original_title: 'Drive',
    poster_path: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '2011-09-15',
    vote_average: 7.6,
    vote_count: 12000,
    genre_ids: [80, 18, 53],
    genres: [
      { id: 80, name: 'Crimen' },
      { id: 53, name: 'Thriller' },
    ],
    overview: 'Un misterioso especialista de cine de Hollywood que trabaja como conductor para criminales por la noche se mete en problemas cuando ayuda a su vecina.',
    original_language: 'en',
    runtime: 100,
    tagline: 'Solo conduce.',
    status: 'Released',
    budget: 15000000,
    revenue: 77000000,
    credits: {
      cast: [
        { id: 1, name: 'Ryan Gosling', character: 'Driver', profile_path: null },
        { id: 26, name: 'Carey Mulligan', character: 'Irene', profile_path: null },
      ],
      crew: [
        { id: 27, name: 'Nicolas Winding Refn', job: 'Director', department: 'Directing' },
      ],
    },
  },
  {
    id: 109,
    title: 'Alien: El Octavo Pasajero',
    original_title: 'Alien',
    poster_path: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600&auto=format&fit=crop',
    backdrop_path: null,
    release_date: '1979-05-25',
    vote_average: 8.1,
    vote_count: 13500,
    genre_ids: [878, 53],
    genres: [
      { id: 878, name: 'Ciencia Ficción' },
    ],
    overview: 'La tripulación de la nave espacial comercial Nostromo es despertada de sus cápsulas de criosueño para investigar una llamada de socorro de una nave alienígena.',
    original_language: 'en',
    runtime: 117,
    tagline: 'En el espacio nadie podrá oír tus gritos.',
    status: 'Released',
    budget: 11000000,
    revenue: 104900000,
    credits: {
      cast: [
        { id: 28, name: 'Sigourney Weaver', character: 'Ripley', profile_path: null },
        { id: 29, name: 'Tom Skerritt', character: 'Dallas', profile_path: null },
      ],
      crew: [
        { id: 30, name: 'Ridley Scott', job: 'Director', department: 'Directing' },
      ],
    },
  },
];
